#!/usr/bin/env bash
# Nginx installation

sudo apt update &&
sudo apt -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Holberton School for the win!" > /var/www/html/index.html &&
sudo /etc/init.d/nginx start
