#!/usr/bin/env bash
# HAproxy installation

sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-1.6

sudo apt-get update -y
sudo apt-get install -y haproxy=1.6.\*

sudo sed -i '$ a\\nlisten http-in\n\tbind *:80\n\tmode http\n\tbalance roundrobin\n\tserver 1225-web-01 18.234.134.195:80\n\tserver 1225-web-02 34.229.78.8:80' /etc/haproxy/haproxy.cfg

sudo service haproxy restart
