#!/usr/bin/env bash
# This script prints "Holberton School" 10 times using if conditionals

i=1

while [ $i -le 100 ]
do
	if [ $((i % 3)) -eq 0 ] && [ $((i % 5)) -eq 0 ]; then
		echo "FizzBuzz"
	elif [ $((i % 3)) -eq 0 ]; then
		echo "Fizz"
	elif [ $((i % 5)) -eq 0 ];then
		echo "Buzz"
	else
		echo "$i"
	fi
	i=$((i + 1))
done
