#!/usr/bin/env bash
# This script prints "Holberton School" 10 times using if conditionals

i=0

while [ $i -lt 10 ]
do
	if [ $i -eq 3 ]; then
		echo "bad luck"
	elif [ $i -eq 7 ]; then
		echo "good luck"
	else
		echo "Holberton School"
	fi
	i=$((i + 1))
done
