#!/usr/bin/env bash
# Ufw - allow only 22, 80 and 443 ports
sudo ufw disable
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow ssh/tcp
sudo ufw allow http/tcp
sudo ufw allow https/tcp
sudo ufw enable
